# Generated by Django 5.0.6 on 2024-05-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_uz', models.TextField(null=True, verbose_name="Ma'lumotlar (Uzbek)")),
                ('info_ru', models.TextField(null=True, verbose_name='Информация (Russian)')),
                ('info_en', models.TextField(null=True, verbose_name='Information (English)')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField()),
                ('Info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_contact.info')),
            ],
        ),
    ]
