# Generated by Django 5.0.6 on 2024-05-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Info',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
