# Generated by Django 5.0.6 on 2024-05-15 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='users',
            name='Another_information',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='Scienfig_degree',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='organization',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
