# Generated by Django 5.0.6 on 2024-05-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_users_phone_number_users_another_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=60)),
                ('Scienfig_degree', models.CharField(max_length=255)),
                ('Another_information', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
