# Generated by Django 5.0.6 on 2024-05-18 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_photo', models.ImageField(upload_to='publications/')),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('publications', models.ManyToManyField(related_name='tags', to='app_puplication.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('publication_text', models.TextField()),
                ('publication_file', models.FileField(blank=True, null=True, upload_to='publication_files/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app_puplication.publication')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app_puplication.tag')),
            ],
        ),
    ]
