# Generated by Django 5.0.6 on 2024-05-19 00:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_puplication', '0003_remove_publicationdetail_tag_publicationdetail_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_ru',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_uz',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicationdetail',
            name='description_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicationdetail',
            name='description_ru',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicationdetail',
            name='description_uz',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicationdetail',
            name='publication_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
