# Generated by Django 5.0.6 on 2024-05-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_puplication', '0004_alter_publication_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
