# Generated by Django 5.0.6 on 2024-05-17 00:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('text_uz', ckeditor.fields.RichTextField()),
                ('text_ru', ckeditor.fields.RichTextField()),
                ('text_en', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=50)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app_requirement.requirement')),
            ],
        ),
    ]
