# Generated by Django 5.0.6 on 2024-05-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(max_length=255, unique=True, verbose_name='Savol (Uzbek)')),
                ('question_ru', models.CharField(max_length=255, unique=True, verbose_name='Вопрос (Russian)')),
                ('question_en', models.CharField(max_length=255, unique=True, verbose_name='Question (English)')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_uz', models.TextField(verbose_name='Javob (Uzbek)')),
                ('answer_ru', models.TextField(verbose_name='Ответ (Russian)')),
                ('answer_en', models.TextField(verbose_name='Answer (English)')),
                ('faq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app_faq.faq')),
            ],
        ),
    ]
