# Generated by Django 5.0.6 on 2024-05-18 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Papers_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name_uz', models.CharField(max_length=255)),
                ('subject_name_ru', models.CharField(max_length=255)),
                ('subject_name_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('papers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_papers.papers')),
            ],
        ),
        migrations.AddField(
            model_name='papers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_papers.papers_category'),
        ),
        migrations.CreateModel(
            name='PapersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('pdffile', models.FileField(upload_to='papers/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_papers.papers_category')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text_uz', models.TextField()),
                ('article_text_ru', models.TextField()),
                ('article_text_en', models.TextField()),
                ('papers_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_papers.papersdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('content_uz', models.TextField()),
                ('content_ru', models.TextField()),
                ('content_en', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_papers.article')),
            ],
        ),
    ]
