# Generated by Django 5.0.6 on 2024-05-18 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_papers', '0003_article_added_by_keywords_added_by_papers_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersdetail',
            name='papers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_papers.papers'),
            preserve_default=False,
        ),
    ]
