# Generated by Django 5.0.6 on 2024-05-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_papers', '0004_papersdetail_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='count',
        ),
    ]
