# Generated by Django 5.0.6 on 2024-05-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_papers', '0005_remove_papers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
