# Generated by Django 5.0.6 on 2024-05-19 00:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_papers', '0008_alter_papers_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_ru',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_uz',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='papersdetail',
            name='description_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='papersdetail',
            name='description_ru',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='papersdetail',
            name='description_uz',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content_ru',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content_uz',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
