# Generated by Django 5.0.6 on 2024-05-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_papers', '0009_alter_article_article_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaperView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('paper_id', models.IntegerField()),
                ('last_viewed', models.DateTimeField()),
            ],
        ),
    ]
